spring:
  application:
    name: auth
  #dataSource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
  #JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  #logging
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        web:
          client:
            RestTemplate: DEBUG
token:
  jwt:
    secret: Kf9uX!7zQa2$rB3cP#dLmV8@eYtNwZxGjHsTrC1o
    header: Authorization
    prefix: Bearer
    access:
      expire-min: 120
    refresh:
      expire-min: 1051200 #2년
